sudo: false
language: node_js
node_js: 10
cache: yarn
deploy:
  provider: npm
  email: felix@stkn.org
  api_key:
    secure: KusqUdY+Q+/20wBf4OJkCgz9mJLN0YoXng87vbrV99GBpLvuz++FgETcfZ8Sazvb+QJ99RxBCbSd4HerUjo4+MJ3HuvCCDq76HcQ52Vno0pB0I6omwzi0Aa/XuqEsi71t7pG2NVN5MZBDSHQAatfO3irWuu2qK/mpU2VW11gfb6kpDizmdFwEd+rOFAXvxjGuQyvAUz3ftf1bUR7+CexC/L6Bn16U49C/VjKUNJlvKMaiqHRiMePr2Na9PNv8TSmEJmLCCCSLYWFXf8VC6NVwp+dTXkKBxDTYzw1hvwgbO268man29L6TNb6pU5FwrVOWN+ROxY6jjPoy6KhmjnEXMRv185HUQ8riMEkoUy/gw0/TRHP2mXcCsCm/TIEtsk1YSU3hh7qu8K4pVJu1kGHNWGuCKW3mnalYoLr8MiINAP6tq855GNmz4ccf9hLj+lc7CIV213yFJrVOlekLMSPBLDpz1Lxb6wWhz+nAbeAn3IEu6um4VhrIDMhET7ozxUeiZ1Bc6FXMJceiK4jjOzBLDXfpLZPxcbnz1MbeyrVBH1KXp4ojsdTcpiV8CSZCVDhsqvtIRxgSog5dHoQV4Ab9RW8TBTIUznl42g8jZHVCCH0ZbLgIWqTXPWrxWHX54pnlR7WeMxH1KaccQdG+ZkMykWhmkXU0pg/mzFFHtZA3BI=
  on:
    tags: true
    repo: cebor/es-promisify
